services:
  web:
    build: .
    restart: always
    ports:
      - "80:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "cd notes_for_goats && python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 