# Generated by Django 4.2.20 on 2025-04-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0003_alter_entity_project_alter_journalentry_project"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Workspace",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="project",
            new_name="workspace",
        ),
        migrations.RenameField(
            model_name="journalentry",
            old_name="project",
            new_name="workspace",
        ),
    ]
