# Generated by Django 4.2.20 on 2025-04-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notekeeper", "0005_relationshiptype_relationship"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relationship",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="relationshiptype",
            options={"ordering": ["workspace", "display_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="relationship",
            unique_together={
                (
                    "workspace",
                    "source_content_type",
                    "source_object_id",
                    "target_content_type",
                    "target_object_id",
                    "relationship_type",
                )
            },
        ),
        migrations.CreateModel(
            name="RelationshipInferenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_bidirectional",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, relationships will be inferred in both directions",
                    ),
                ),
                (
                    "auto_update",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically update inferred relationships when source relationships change",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inferred_relationship_type",
                    models.ForeignKey(
                        help_text="Create this relationship between the entities",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inferred_inference_rules",
                        to="notekeeper.relationshiptype",
                    ),
                ),
                (
                    "source_relationship_type",
                    models.ForeignKey(
                        help_text="When two entities share this relationship with a common target",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_inference_rules",
                        to="notekeeper.relationshiptype",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_rules",
                        to="notekeeper.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace", "name"],
                "unique_together": {("workspace", "name")},
            },
        ),
    ]
