# Generated by Django 4.2.20 on 2025-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0006_alter_relationship_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshiptype",
            name="is_bidirectional",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this is treated as a single bidirectional relationship between entities",
            ),
        ),
    ]
