# Generated by Django 4.2.20 on 2025-04-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0007_relationshiptype_is_bidirectional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationshipinferencerule",
            name="is_bidirectional",
        ),
    ]
