# Generated by Django 4.2.20 on 2025-04-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0008_remove_relationshipinferencerule_is_bidirectional"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of tags (e.g., 'me,myself,I')",
                max_length=255,
            ),
        ),
    ]
