# Generated by Django 4.2.20 on 2025-04-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0009_entity_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-timestamp"],
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.AlterField(
            model_name="entity",
            name="tags",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="referenced_entities",
            field=models.ManyToManyField(
                blank=True, related_name="journal_notes", to="notekeeper.entity"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_notes",
                to="notekeeper.workspace",
            ),
        ),
    ]
