# Generated by Django 4.2.20 on 2025-04-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0010_alter_journalentry_options_alter_entity_tags_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JournalEntry",
            new_name="NotesEntry",
        ),
    ]
