# Generated by Django 4.2.20 on 2025-04-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0011_rename_journalentry_notesentry"),
    ]

    operations = []
