# Generated by Django 4.2.20 on 2025-04-18 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0012_rename_entity_notes_to_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="notesentry",
            name="referenced_entities",
            field=models.ManyToManyField(
                blank=True, related_name="note_notes", to="notekeeper.entity"
            ),
        ),
        migrations.AlterField(
            model_name="notesentry",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="note_notes",
                to="notekeeper.workspace",
            ),
        ),
        migrations.DeleteModel(
            name="CalendarEvent",
        ),
    ]
