# Generated by Django 4.2.20 on 2025-04-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notekeeper",
            "0013_entity_details_alter_notesentry_referenced_entities_and_more",
        ),
    ]

    operations = []
