# Generated by Django 4.2.20 on 2025-04-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0015_copy_notes_to_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="notes",
        ),
    ]
