# Generated by Django 4.2.20 on 2025-04-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0016_remove_entity_notes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NotesEntry",
            new_name="Note",
        ),
    ]
