# Generated by Django 4.2.20 on 2025-04-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0019_copy_relationship_notes_to_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationship",
            name="notes",
        ),
    ]
