# Generated by Django 4.2.20 on 2025-04-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0020_remove_relationship_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtags",
                        to="notekeeper.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("workspace", "name")},
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="entity_tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_entities", to="notekeeper.tag"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="note_tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_notes", to="notekeeper.tag"
            ),
        ),
    ]
