# Generated by Django 4.2.20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notekeeper', '0023_copy_entity_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='tags',
        ),
    ] 