# Generated by Django 4.2.20 on 2025-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0026_rename_note_tags_to_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tagged_notes", to="notekeeper.tag"
            ),
        ),
    ]
