# Generated by Django 4.2.20 on 2025-04-21 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0021_userpreference"),
        ("notekeeper", "0027_alter_note_tags"),
    ]

    operations = []
