# Generated by Django 4.2.20 on 2025-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0029_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="use_direct_prompt",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
