# Generated by Django 4.2.20 on 2025-04-22 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0030_userpreference_use_direct_prompt_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="notekeeper.note",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="notekeeper.entity",
                    ),
                ),
            ],
        ),
    ]
