# Generated by Django 4.2.20 on 2025-04-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0031_noteembedding_entityembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="noteembedding",
            name="section_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="noteembedding",
            name="section_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noteembedding",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="notekeeper.note",
            ),
        ),
    ]
