# Generated by Django 4.2.20 on 2025-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0032_noteembedding_section_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="file_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the imported file",
                max_length=255,
                null=True,
            ),
        ),
    ]
