# Generated by Django 4.2.20 on 2025-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notekeeper", "0033_note_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Job title or role (only for Person entities)",
                max_length=100,
            ),
        ),
    ]
